### PR TITLE
Added device_id to sessions-table and login/session-functions

### PR DESCRIPTION
**Pull request by louis123562**
see https://github.com/PHPAuth/PHPAuth/issues/408 why i need it.

### CODE REVIEW

**Comment by Conver** [comment]
I can see why you would need it, I'm just not sure it should be added in the main code, as not many would need this. Should properly be added as an addon of some kind. Maybe create an article in the wiki telling how to add it if people need it.

**Comment by louis123562** [comment]
is there a way of creating an addon? Is there an example somewhere? Alternatevly i would keep in my forked repo.

**Comment by Conver** [comment]
That's something we are still working on, but see this: https://github.com/PHPAuth/PHPAuth/blob/master/Auth.php#L180

You could easily just use the $params = [] function, to add it under creation, then it's just a matter of having the field in the db table.

**Comment by louis123562** [comment]
Okay, but there is no $param array yet in the function definitions, sould i add it to the end and keep the original parameters (1) or should integrate some/all/unnecessary parameters into the array (2)?

```
1.
    public function login($email, $password, $remember = 0, $captcha_response = null, $param = [])

2.
    public function login($email, $password, $param = [])
  
```

**Comment by louis123562** [comment]
okay i think (2) is stupid

**Pull request closed without merging**
