### PR TITLE
User Roles

### PR DESCRIPTION
**Pull request by MatteoGheza**

### CODE REVIEW

**Comment by KarelWintersky** [comment]
I think, role **must be** additional parameter.

**Comment by KarelWintersky** [comment]
So, this brokes compatibility

**Comment by MatteoGheza** [comment]
Yes, exactly

**Comment by MatteoGheza** [comment]
I can change the position of "$role"

**Comment by MatteoGheza** [comment]
`register($email, $password, $repeatpassword, $params = [], $captcha_response = null, $use_email_activation = null, $role=null)`
 `addUser($email, $password, $params = [], &$use_email_activation, $role=null)`
If role is null -> role = 0

**Comment by MatteoGheza** [comment]
But, this brokes compatibility with old db schema

**Comment by MatteoGheza** [comment]
My idea is adding a option in config, `enable_roles`: if the value in config equals to 1, the `addUser` query updates `role`.
For example:
```
if(isset($this->config->enable_roles)){
            if($this->config->enable_roles){
                $params["role"] = $role; 
            }
}
```
before custom params

**Comment by MatteoGheza** [comment]
@KarelWintersky can you try these commits?

**Comment by KarelWintersky** [comment]
Why not a:
```
if(isset($this->config->enable_roles) && $this->config->enable_roles)
{
                $params["role"] = $role; 
}
```
?

**Comment by KarelWintersky** [comment]
Anyway, I think, your roles implementation is not required. Role can be custom param. And `role` as single integer value is VERY simple. 

As a custom param, developer can implement 'role' column as enum or varchar. 

Hardcoding this as simple int value is BAD solution.

**Comment by KarelWintersky** [comment]
I'll reject this.
@liamjack

**Comment by louis123562** [comment]
I agree to karel.

**Pull request closed without merging**
