### PR TITLE
BUGFIX: username column not exist #390

### PR DESCRIPTION
**Pull request by turbopixel**
I have removed the column in Select. This is the only place where a username is used.

### CODE REVIEW

**Review by louis123562 — APPROVED** [review]
nice!

**Comment by Conver** [comment]
I think we should do it the other way around, so that username is part of PHPAuth.

9/10 of my projects which uses PHP uses username in its.

What do you guys think? I would prefer we add it to the whole PHPAuth than removing it?

**Comment by louis123562** [comment]
my projects focus on email, but if the username can be the same as the email, i guess this would be okay.

**Comment by turbopixel** [comment]
Basically I would prefer email and password and I would add an optional field "username" to the table. In the registration and login, the username can be given optionally afterwards. A good example is delight-im/PHP-Auth: https://github.com/delight-im/PHP-Auth/blob/master/src/Auth.php#L319 There is a username optional.

The problem what I see is that you have to check a username for everything. Which characters are allowed in the username? Are special characters ok or do you have to remove them?

**Comment by Conver** [comment]
@turbopixel  Yes! That way is good for me too.

**Comment by Conver** [comment]
@all-contributors please add turbopixel for code

**Pull request merged**
