### PR TITLE
rewritten  Christin Milloy suppression email

### PR DESCRIPTION
**Pull request by mooztik**
rewritten send mail option
renamed `$suppressed` varname to a more clearer naming `$sendmail`
added manual control to send mail 
removed language overwrite and set text result from correponding methods
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/122%23issuecomment-142905643%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/122%23issuecomment-142905643%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20have%20a%20question%20about%20the%20mail%20suppression%3A%20if%20we%20set%20%24sendmail%20%3D%20false%20the%20activation%20is%20still%20working%3B%20how%20can%20the%20user%20activate%20his%20account%20without%20the%20generated%20key%3F%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-09-24T11%3A43%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4438193%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/bugada%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/PHPAuth/PHPAuth/pull/122#issuecomment-142905643'>General Comment</a></b>
- <a href='https://github.com/bugada'></a> I have a question about the mail suppression: if we set $sendmail = false the activation is still working; how can the user activate his account without the generated key?

<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/122?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/122?approve=1'></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/122'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by Conver** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/PHPAuth/PHPAuth/pull/122'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by bugada** [comment]
I have a question about the mail suppression: if we set $sendmail = false the activation is still working; how can the user activate his account without the generated key?

**Comment by Conver** [comment]
:shipit:

**Comment by mooztik** [comment]
Good point bugada .
i m using phpauth for a little intra-net app. there's no need for mails or  activation keys. i'm the only one to create accounts, then i m not using it

the simpler way : if sendmail is set TRUE, account is automaticly activated.
i don't think it's the best way, but actually it fix this little problem :)

**Pull request merged**
