### PR TITLE
Add configuration option to allow multiple sessions for one user

### PR DESCRIPTION
**Pull request by bletham**
As discussed in #326.

Added a unit test which passes.

I set the default to `false`, which is the current behavior.

### CODE REVIEW

**Comment by KarelWintersky** [comment]
Thank you!

**Comment by Conver** [comment]
I've reverted the PR until it also has this fix.

**Comment by bletham** [comment]
@Conver thanks, I'll submit a new PR with the fix.

**Comment by bletham** [comment]
Updates in #329

**Pull request merged**
