### PR TITLE
Namespace added

### PR DESCRIPTION
**Pull request by KarelWintersky**
+ Namespace added for auth.class.php and config.class.php
+ fixed README.md
+ fixed PHPDocs

### CODE REVIEW

**Comment by KarelWintersky** [comment]
It is a little trick: 

We can call `$config = new Config($dbh, "config_table");` **always** 

OR 

we can *patch* `private $phpauth_config_table` manually and calls `$config = new Config($dbh);` without any additional values (special for lazy coders like me ;-) )
----
```
        if (func_num_args() > 1)
            $this->phpauth_config_table = $config_table;
```
REQUIRED!!!

Because if private $config_table patched manually, and we omit argument $configtable here:
```
$phpauth_config = PHPAuth\Config($dbh);
```
(that declared as 
```
function __construct($dbh, $config_table = 'config') ... 
```
)

private value $config_table WILL BE ALWAYS OVERRITTEN with default value 'config'.

**Comment by KarelWintersky** [comment]
Rejected?

**Comment by KarelWintersky** [comment]
https://github.com/PHPAuth/PHPAuth/issues/73

**Comment by Conver** [comment]
Sorry, wasn't meant to close it. just hadn't the time to check the PR.

**Comment by KarelWintersky** [comment]
I added 
```
if (version_compare(phpversion(), '5.4.0', '<')) {
            die('PHP 5.4.0 required for PHPAuth engine!');
        }
```
to PHPAuth\Auth::__construct() and all other lines shifted down.

**Comment by Conver** [comment]
There is just lots of changes to go tho, will see if I can get time to check it ASAP.

**Comment by KarelWintersky** [comment]
well, you can reject this PR again and I'll make new PR **only** with namespace changes.

My changes are:
1. added `namespace PHPAuth;`
2. all `PDO::FETCH_ASSOC`  replaced by `\PDO::FETCH_ASSOC` (used root namespace)
3. `$mail = new PHPMailer;` replaced by `$mail = new \PHPMailer;`
4. all `/* ` comment starts changed to valid PHPDoc code: `/**`

**Comment by Conver** [comment]
Those changes, are those the one in this PR?

**Comment by KarelWintersky** [comment]
Yes, of course!

**Comment by Conver** [comment]
Okay.. Those changes are okay. of course.. 

The PR ain't merge able anymore, so I'll cancel/close it, and maybe you can submut a new PR?

**Comment by KarelWintersky** [comment]
yeah, I can.

**Comment by Conver** [comment]
Perfect, thanks.

**Pull request closed without merging**
