### PR TITLE
Fix typo (English).

### PR DESCRIPTION
**Pull request by Maikuolan**
"Are" for plural. "Is" for singular.

### CODE REVIEW

**Comment by KarelWintersky** [comment]
Accepted.

Please, fix also https://github.com/PHPAuth/PHPAuth.l10n

**Comment by KarelWintersky** [comment]
"Email and password are incorrect" but "Email or password IS incorrect" ?

**Comment by Maikuolan** [comment]
(In cases where it's ambiguous, or where the grammar rules don't help, e.g., when "/" is intended to convey "and/or", instead of "and" or "or", or when we don't know whether it's plural or singular, just use whichever sounds better).

**Comment by KarelWintersky** [comment]
Do you think smth about https://github.com/PHPAuth/PHPAuth/discussions/541 ? ;-)

**Pull request merged**
