### PR TITLE
Add Session Authentication to the PHPAuth Core Class

### PR DESCRIPTION
**Pull request by rondeo-balos**
SessionAuth class
- Overrides the Auth class to provide session-based authentication instead of cookie-based.

### CODE REVIEW

**Comment by KarelWintersky** [comment]
namespace PHPAuth requireed

**Comment by rondeo-balos** [comment]
Added namespace PHPAuth; to the SessionAuth class

**Comment by KarelWintersky** [comment]
What do you think about implementing this functionality inside PHPAuth Core class? 

with a config option changing behavior?

**Comment by rondeo-balos** [comment]
This is a good idea! Adding this functionality to the core is much better. I'll close this PR, and create another one. Or should you guys do it instead? 👌

**Comment by JapCLoN** [comment]
@rondeo-balos, I would appreciate it a lot if you could create it and make a PR for it :)

Sadly much of us are pretty busy lately, so I think it will go much faster if you can do it.

**Comment by rondeo-balos** [comment]
Added Session Authentication to the PHPAuth Core Class. Users can now choose between using a Session or a Cookie by setting the 'use_session' configuration option to 1 or 0.

Unit Tests Before
unit test before

Unit Tests After
unit test after

**Comment by JapCLoN** [comment]
approved and merged, thanks a lot!

@KarelWintersky, will you do the releases part please?

**Comment by KarelWintersky** [comment]
Ok. A bit later.

**Comment by KarelWintersky** [comment]
@JapCLoN , @rondeo-balos  PHPAuth 1.4.5 released

**Pull request merged**
