### PR TITLE
Added ability to add additional profile fields in the registration.

### PR DESCRIPTION
**Pull request by Bathead**
My some changes

### CODE REVIEW

**Comment by Conver** [comment]
I like your PR, good work!

I just need you to change the way you are using PDO is this PR, so that its like the other in the class.

You are using the $query->bindParam(':id', $uid); .. Which is good, no problem there.. its just not the way its done in the rest of the code, and we need to make it the same all over the class, so that non tech can do stuff too.. I can edit it for you aswell, but though its easier you do it.

Thanks for the PR btw, please keep them coming. hehe.

**Comment by Bathead** [comment]
Thanks for review! Please see my changes and fixes.

**Comment by Conver** [comment]
@Bathead Perfect, thank! glad to see..

Hope to see more PR's from you, nice you.

**Comment by Conver** [comment]
@Bathead, it would be very great if you could add a little bit of text in the readme how to use this.

**Pull request merged**
