### PR TITLE
Make current password parameter mandatory for changePassword

### PR DESCRIPTION
**Pull request by bmsimons**
Good afternoon,

This PR makes changing a user's password possible without the current password parameter being mandatory. I needed this because administrators of my application needed to be able to do a forced password reset on a specific user, without having to send the user a password recovery email.

### CODE REVIEW

**Comment by liamjack** [comment]
There is indeed a need for "forced password resets" by administrators, but with this pull request you are changing the "Change password" method for all users, this now means that on an existing site implementing PHPAuth the current password field is no longer required, and a user only needs to be logged in to change their password, leaving the "current password" field empty will work. I'm not sure this is the right way to go about it.

**Comment by Conver** [comment]
Sorry @liamjack, I was to fast then.

**Comment by bmsimons** [comment]
Good catch, but a user filling in an empty current password fields returns in an empty string, and not in a parameter casted to NULL. That means that only a developer can specify if it is needed to accept the 'current password' parameter. Please correct me if I'm wrong.

**Comment by liamjack** [comment]
@bmsimons True, but you can't count on it always being an empty string (interpretation depends on OS, Web server, PHP version...), maybe a better solution would be a dedicated method with some sort of role system ?

**Comment by Tharre** [comment]
@liamjack what exactly do you mean with 'role system'?

Also, any specific reason why issues are disabled for this repo? Too much spam?
Makes it somewhat difficult to discuss problems before implementing a solution.

**Comment by liamjack** [comment]
@Tharre By role system I mean adding an "admin" role so that only administrators can force password changes.

Issues were disabled because of excessive amounts of spam involving basic questions that were mostly covered by the README or previous issues. In the end no-one even looked at the issues and they just piled up.

**Pull request merged**
