### PR TITLE
Augmenting the suppressed functionality with messaging and languages (properly this time)

### PR DESCRIPTION
**Pull request by ChristinMilloy**
Sorry about the earlier confusion, this commit should merge correctly and adds back in the messaging features for both suppression flags.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/120%23issuecomment-142048539%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/120%23issuecomment-142048864%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/120%23issuecomment-142049363%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/120%23issuecomment-142049645%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/120%23issuecomment-142050908%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/120%23issuecomment-142052281%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/120%23issuecomment-142052676%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/120%23issuecomment-142048539%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Line%2037%20should%20not%20be%20removed%20from%20the%20database%20%22%2C%20%22created_at%22%3A%20%222015-09-21T17%3A22%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5149016%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/JacquesLoubser%22%7D%7D%2C%20%7B%22body%22%3A%20%22You%27re%20correct%2C%20it%20happened%20by%20accident%20in%20my%20revert%20and%20merge.%20Let%20me%20fix%20it.%22%2C%20%22created_at%22%3A%20%222015-09-21T17%3A24%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4187179%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ChristinMilloy%22%7D%7D%2C%20%7B%22body%22%3A%20%22checking%22%2C%20%22created_at%22%3A%20%222015-09-21T17%3A26%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Conver%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40ChristinMilloy%20why%20don%27t%20you%20hard%20reset%20your%20fork%2C%20and%20try%20again%3F%20If%20you%20want%20I%20can%20send%20the%20commands.%22%2C%20%22created_at%22%3A%20%222015-09-21T17%3A27%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5149016%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/JacquesLoubser%22%7D%7D%2C%20%7B%22body%22%3A%20%22Sure%2C%20that%20would%20be%20helpful.%20I%27m%20having%20a%20really%20hard%20time%20keeping%20everything%20synced%20up.%22%2C%20%22created_at%22%3A%20%222015-09-21T17%3A32%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4187179%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ChristinMilloy%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40ChristinMilloy%2C%20have%20you%20seen%20the%20invite%20to%20become%20a%20member%20of%20the%20development%20team%3F%22%2C%20%22created_at%22%3A%20%222015-09-21T17%3A35%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Conver%22%7D%7D%2C%20%7B%22body%22%3A%20%22From%20the%20command%20line%20%28once%20only%29%3A%5Cr%5Cn%60%60%60%5Cr%5Cngit%20remote%20add%20upstream%20https%3A//github.com/PHPAuth/PHPAuth.git%5Cr%5Cn%60%60%60%5Cr%5Cn%5Cr%5CnFrom%20the%20command%20line%20%28to%20reset%29%3A%5Cr%5Cn%5Cr%5Cn%60%60%60%5Cr%5Cngit%20fetch%20upstream%5Cr%5Cngit%20checkout%20master%5Cr%5Cngit%20reset%20--hard%20upstream/master%20%20%5Cr%5Cngit%20push%20origin%20master%20--force%20%5Cr%5Cn%60%60%60%5Cr%5Cn%5Cr%5CnUpdating%20my%20fork%20took%20me%20most%20of%20a%20day%20to%20work%20out%2C%20so%20don%27t%20worry%20%3B%29%22%2C%20%22created_at%22%3A%20%222015-09-21T17%3A36%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5149016%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/JacquesLoubser%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/PHPAuth/PHPAuth/pull/120#issuecomment-142048539'>General Comment</a></b>
- <a href='https://github.com/JacquesLoubser'></a> Line 37 should not be removed from the database
- <a href='https://github.com/ChristinMilloy'></a> You're correct, it happened by accident in my revert and merge. Let me fix it.
- <a href='https://github.com/Conver'></a> checking
- <a href='https://github.com/JacquesLoubser'></a> @ChristinMilloy why don't you hard reset your fork, and try again? If you want I can send the commands.
- <a href='https://github.com/ChristinMilloy'></a> Sure, that would be helpful. I'm having a really hard time keeping everything synced up.
- <a href='https://github.com/Conver'></a> @ChristinMilloy, have you seen the invite to become a member of the development team?
- <a href='https://github.com/JacquesLoubser'></a> From the command line (once only):
```
git remote add upstream https://github.com/PHPAuth/PHPAuth.git
```
From the command line (to reset):
```
git fetch upstream
git checkout master
git reset --hard upstream/master
git push origin master --force
```
Updating my fork took me most of a day to work out, so don't worry ;)

<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/120?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/120?approve=1'></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/120'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by Conver** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/PHPAuth/PHPAuth/pull/120'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by JacquesLoubser** [comment]
Line 37 should not be removed from the database

**Comment by ChristinMilloy** [comment]
You're correct, it happened by accident in my revert and merge. Let me fix it.

**Comment by Conver** [comment]
checking

**Comment by JacquesLoubser** [comment]
@ChristinMilloy why don't you hard reset your fork, and try again? If you want I can send the commands.

**Comment by ChristinMilloy** [comment]
Sure, that would be helpful. I'm having a really hard time keeping everything synced up.

**Comment by Conver** [comment]
@ChristinMilloy, have you seen the invite to become a member of the development team?

**Comment by JacquesLoubser** [comment]
From the command line (once only):
```
git remote add upstream https://github.com/PHPAuth/PHPAuth.git
```

From the command line (to reset):

```
git fetch upstream
git checkout master
git reset --hard upstream/master  
git push origin master --force 
```

Updating my fork took me most of a day to work out, so don't worry ;)

**Pull request closed without merging**
