### PR TITLE
Removed deprected code, optimisation DB, opt. code

### PR DESCRIPTION
**Pull request by KarelWintersky**
Removed deprected code, optimisation DB, opt. code

### CODE REVIEW

**Comment by Conver** [comment]
"Conver added the in progress label 3 minutes ago"

That one was a fail, but I'm unable to remove it again somehow.

btw, you are doing a really good job!

**Comment by KarelWintersky** [comment]
@Conver I need help with Informix DB Scheme , MS SQL DB Scheme and PostgreSQL DB Scheme

I don't know how declare `int(10) unsigned` and `enum('A', 'B')` types

**Comment by Conver** [comment]
@KarelWintersky I'll see if I can look into that today, I do not use those DBs, so I dont know how it works.

**Comment by KarelWintersky** [comment]
> you are doing a really good job!

'cause I need in PHPAuth via composer for my microframework ;)

**Pull request merged**
