### PR TITLE
hardcoded link to config table replaced by private config value

### PR DESCRIPTION
**Pull request by KarelWintersky**
may be used in webapps with a lot of tables

### CODE REVIEW

**Comment by Conver** [comment]
This is another good PR, tho I would like it to be a bit more dynamic, maybe but this set inside __construct, so that when calling phpauth, you can either tell a config table, or it will use the default one. follow me?

**Comment by KarelWintersky** [comment]
Yeah. I  have some ideas...

**Comment by Conver** [comment]
Perfect, else let me know. and I'll update it.

**Comment by KarelWintersky** [comment]
See new commit. 

It is a little trick: 
We can call `$config = new Config($dbh, "config_table");` **always** 
OR 
we can *patch* `private $phpauth_config_table` manually and calls `$config = new Config($dbh);` without any additional values (special for lazy coders like me ;-) )

PS Sorry, I have not enough expirience with branches and PRs ;)

**Pull request merged**
