### PR TITLE
fixed travis problem

### PR DESCRIPTION
**Pull request by mooztik**
found it ! :)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/129%23issuecomment-145400469%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/129%23issuecomment-145400573%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/129%23issuecomment-145400894%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/129%23issuecomment-145401276%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/129%23issuecomment-145402367%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/129%23issuecomment-145400469%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22The%20biggest%20problem%20is%20to%20create%20a%20database%20and%20push%20info%20into%20it%2C%20so%20that%20phpunit%20can%20run%20tests.%22%2C%20%22created_at%22%3A%20%222015-10-04T23%3A15%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5149016%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/JacquesLoubser%22%7D%7D%2C%20%7B%22body%22%3A%20%22i%20m%20looking%20a%20it.%20a%22%2C%20%22created_at%22%3A%20%222015-10-04T23%3A17%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1687538%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/mooztik%22%7D%7D%2C%20%7B%22body%22%3A%20%22Haha%20okay%20yes%20no%20more%20error.%22%2C%20%22created_at%22%3A%20%222015-10-04T23%3A24%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5149016%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/JacquesLoubser%22%7D%7D%2C%20%7B%22body%22%3A%20%22now%20big%20stodgy%20read%5Cr%5Cnhttps%3A//phpunit.de/manual/current/en/database.html%5Cr%5Cnbut%20now%20it%20time%20to%20sleep...%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-10-04T23%3A30%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1687538%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/mooztik%22%7D%7D%2C%20%7B%22body%22%3A%20%22OK%20that%20looks%20great.%20I%20was%20trying%20to%20get%20Travis%20to%20do%20the%20setup%2C%20but%20phpunit%20seems%20to%20be%20better.%20%22%2C%20%22created_at%22%3A%20%222015-10-04T23%3A34%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5149016%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/JacquesLoubser%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/PHPAuth/PHPAuth/pull/129#issuecomment-145400469'>General Comment</a></b>
- <a href='https://github.com/JacquesLoubser'></a> The biggest problem is to create a database and push info into it, so that phpunit can run tests.
- <a href='https://github.com/mooztik'></a> i m looking a it. a
- <a href='https://github.com/JacquesLoubser'></a> Haha okay yes no more error.
- <a href='https://github.com/mooztik'></a> now big stodgy read
https://phpunit.de/manual/current/en/database.html
but now it time to sleep...
- <a href='https://github.com/JacquesLoubser'></a> OK that looks great. I was trying to get Travis to do the setup, but phpunit seems to be better.

<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/129?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/129?approve=1'></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/129'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by Conver** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/PHPAuth/PHPAuth/pull/129'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by JacquesLoubser** [comment]
The biggest problem is to create a database and push info into it, so that phpunit can run tests.

**Comment by mooztik** [comment]
i m looking a it. a

**Comment by JacquesLoubser** [comment]
Haha okay yes no more error.

**Comment by mooztik** [comment]
now big stodgy read
https://phpunit.de/manual/current/en/database.html
but now it time to sleep...

**Comment by JacquesLoubser** [comment]
OK that looks great. I was trying to get Travis to do the setup, but phpunit seems to be better.

**Pull request merged**
