### PR TITLE
Update Auth.php

### PR DESCRIPTION
**Pull request by Marian-Kechlibar**
The e-mails sent by PHPMailer will now display non-ASCII characters correctly. Tested in the Czech language.

### CODE REVIEW

**Comment by Conver** [comment]
It should be saved in db, and then taken from config with:
````$mail->CharSet = $this->config->mail_charset;````

Can I get you to update the PR?

**Comment by Marian-Kechlibar** [comment]
I will try.

**Comment by Marian-Kechlibar** [comment]
I have run into problems. 

There seems to be some version conflict. On my system I used the version from composer, which is 1.1. That did not matter for the Czech localization, which is pretty separate from the rest of the code, but it mattered for the source code itself, where significant changes have been made since. I will try to fix it somehow locally.

**Comment by Marian-Kechlibar** [comment]
So I tried simply to upload the latest source of PHPAuth to my local server, overwrite the "composer" installation and make my edits there, but now the execution of the code fails with the following error:

 PHP Fatal error:  Uncaught Error: Class 'PHPMailer\\PHPMailer\\PHPMailer' not found in /var/www/html/vendor/phpauth/phpauth/Auth.php:793\nStack trace:\n#0 /var/www/html/vendor/phpauth/phpauth/Auth.php(544): 

I am not sure how "composer" works, I only used it for the first time today. Does it do something during the require action to resolve the dependency of PHPAuth on PHPMailer?

**Comment by Conver** [comment]
Composer just installs the needed classes for PHPAuth, you can simple just add https://github.com/PHPMailer/PHPMailer by yourself, very easy.

If you use smtp, then you'll only need 2 files: class.phpmailer.php & class.smtp.php

**Comment by Marian-Kechlibar** [comment]
Well, I must say I am a bit confused right now.
I originally used composer to install PHPAuth and all the dependencies for it, including PHPMailer.
PHPMailer still sits happily where it was installed (also vendor/phpmailer...), no changes there at all. As long as I use the PHPAuth scripts provided by composer, everything runs smoothly.
As soon as I replace them with current scripts from the master/, even without any edits on my side (vanilla code), the code which should instantiate the new PHPMailer fails with the message above.

I am not really a PHP person; in C, I would say that I am missing a necessary declaration. But why? The library just sits there as before.

How come that the PHPMailer works with the older version, but not with the newer one? Are the version requirements different? Does newer PHPAuth need newer PHPMailer?

**Comment by Marian-Kechlibar** [comment]
So I started comparing those source codes and I found the following differences in Auth.php.

1. In the old version 1.1, there is no "use PHPMailer\PHPMailer\PHPMailer" line at the beginning of the file.

2. The PHP Mailer is instantiated as follows: "$mail = new \PHPMailer", so there is an extra backslash before name of the class.

I will try to modify my local copy of the newer code like this and I will report what it does.

**Comment by Marian-Kechlibar** [comment]
There does not seem to be any easy way how to test the new source code on my server.

I simply edited the contemporary source files and committed them, and I made similar changes on my local server for the older version of PHPAuth.

Please feel free to adopt this current Pull Request, but I haven't seen it running, though the changes are pretty straightforward.

**Pull request merged**
