### PR TITLE
Reimplemented language messages for suppressed emails

### PR DESCRIPTION
**Pull request by ChristinMilloy**
This time completely hard reset my local master first per JacquesLoubser.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/121%23issuecomment-142060232%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/121%23issuecomment-142061793%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/121%23issuecomment-142063214%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/121%23issuecomment-142060232%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22What%20is%20your%20PR%20meant%20to%20do%3F%5Cr%5Cn%5Cr%5CnI%20dont%20really%20see%20anything%20beside%20adding%20%60%24this-%3Elang%5B%27reset_requested%27%5D%3D%24this-%3Elang%5B%27reset_requested_emailmessage_suppressed%27%5D%3B%60%20%3F%22%2C%20%22created_at%22%3A%20%222015-09-21T17%3A53%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Conver%22%7D%7D%2C%20%7B%22body%22%3A%20%22The%20idea%20is%20that%20it%20changes%20the%20output%20messages%20when%20email%20is%20suppressed%20so%5Cnthat%20it%20doesn%27t%20tell%20the%20user%20%5C%22email%20was%20sent.%5C%22%5Cn%5CnI%20put%20in%20alternate%20messages%20for%20both%20states%20in%20all%20languages.%5Cn%5CnOn%20Mon%2C%20Sep%2021%2C%202015%2C%2013%3A53%20Geekologist%20%3Cnotifications%40github.com%3E%20wrote%3A%5Cn%5Cn%3E%20What%20is%20your%20PR%20meant%20to%20do%3F%5Cn%3E%5Cn%3E%20I%20dont%20really%20see%20anything%20beside%20adding%5Cn%3E%20%24this-%3Elang%5B%27reset_requested%27%5D%3D%24this-%3Elang%5B%27reset_requested_emailmessage_suppressed%27%5D%3B%5Cn%3E%20%3F%5Cn%3E%5Cn%3E%20%5Cu2014%5Cn%3E%20Reply%20to%20this%20email%20directly%20or%20view%20it%20on%20GitHub%5Cn%3E%20%3Chttps%3A//github.com/PHPAuth/PHPAuth/pull/121%23issuecomment-142060232%3E.%5Cn%3E%5Cn%22%2C%20%22created_at%22%3A%20%222015-09-21T18%3A00%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4187179%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ChristinMilloy%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-09-21T18%3A05%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Conver%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/Conver%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/Conver'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/PHPAuth/PHPAuth/pull/121#issuecomment-142060232'>General Comment</a></b>
- <a href='https://github.com/Conver'></a> What is your PR meant to do?
I dont really see anything beside adding `$this->lang['reset_requested']=$this->lang['reset_requested_emailmessage_suppressed'];` ?
- <a href='https://github.com/ChristinMilloy'></a> The idea is that it changes the output messages when email is suppressed so
that it doesn't tell the user "email was sent."
I put in alternate messages for both states in all languages.
On Mon, Sep 21, 2015, 13:53 Geekologist <notifications@github.com> wrote:
> What is your PR meant to do?
>
> I dont really see anything beside adding
> $this->lang['reset_requested']=$this->lang['reset_requested_emailmessage_suppressed'];
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PHPAuth/PHPAuth/pull/121#issuecomment-142060232>.
>

<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/121?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/121?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/121?approve=0'></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/121'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by Conver** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/PHPAuth/PHPAuth/pull/121'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Conver** [comment]
What is your PR meant to do?

I dont really see anything beside adding `$this->lang['reset_requested']=$this->lang['reset_requested_emailmessage_suppressed'];` ?

**Comment by ChristinMilloy** [comment]
The idea is that it changes the output messages when email is suppressed so
that it doesn't tell the user "email was sent."

I put in alternate messages for both states in all languages.

**Comment by Conver** [comment]
:shipit:

**Pull request merged**
