### PR TITLE
Namespace PHPAuth added.

### PR DESCRIPTION
**Pull request by KarelWintersky**
+ namespace for `auth.class.php` added
+ namespace for `config.class.php` added
+ fixed README.md
+ fixed PHPDocs

### CODE REVIEW

**Comment by Conver** [comment]
Looks good.. Can you tell me why its required to have PHP vers 5.4 or above?

I don't recall we've added some code which require 5.4 or above, only the password function, but there is a fix for that.

Please clarify and I'll accept the PR :)

**Comment by Conver** [comment]
P.S been a while since I've deep looked into PHPAuth, so might just be me forgetting something (:

**Comment by KarelWintersky** [comment]
> Can you tell me why its required to have PHP vers 5.4 or above?

because you use `anyfunction(param)['isactive']` 

PHP 5.4 : Function array dereferencing has been added, e.g. foo()[0]. 
http://php.net/manual/en/migration54.new-features.php

**Comment by Conver** [comment]
Thanks.

**Pull request merged**
