### PR TITLE
Missing translation for  account_not_found

### PR DESCRIPTION
**Pull request by vktechnology**
Translation for account_not_found
Auth.php
Method public function login  
...
      if (!$uid) {
            $this->addAttempt();
            $return['message'] = $this->__lang("account_not_found");

            return $return;
        }

### CODE REVIEW

**Comment by louis123562** [comment]
which language ?

**Comment by vktechnology** [comment]
Hi

on /language/en_GB.php  is missing  $lang['account_not_found']
then i added 

$lang['account_not_found'] = "No account found with that email address.";

**Comment by louis123562** [comment]
I would recommend to something like this: "There is no account matching the given mail address."

**Comment by vktechnology** [comment]
Good idea for "There is no account matching the given mail address."

**Pull request merged**
