### PR TITLE
WIP: Move translations to SQL

### PR DESCRIPTION
**Pull request by kungknut**
I suggest the language translations are moved to the sql-database and maybe we can write an own class handling them, or is it sufficient to write a function within the `Auth`-class? Whatever solution it would make it possible to call translations using `$this->lang->getLang("system_error", "sv")` or `$this-getLang("system_error", "sv")` respectively.

Two new settings would also be added to the table `config`, `language_preferred` and `language_fallback`. In turn this means the function would return the fallback language translation if no translation are found in the preferred language, if fallback is not found, it will have to throw an error.

Example of sql-table layout (MySQL):

Table `translations`:

| Column name | Data type | Comment |
| -------- | -------- | -------- |
| id | int(11) | String id |
| lang | int(11) | Reference to `languages` |
| lang_key | varchar(255) | Key, eg. `system_error` |
| text | text | Translated string |

Table `languages`:

| Column name | Data type | Comment |
| -------- | -------- | -------- |
| id | int(11) | Language id |
| lang | varchar(2) | Language code eg. `en`, `sv` etc. |

What do you guys think? I haven't started working on this yet - waiting for your feedback.

Cheers

### CODE REVIEW

**Comment by Conver** [comment]
Will language be loaded on obj creation? Or will it look lang table on every language request? The latter will be overlill with to many db lookups.

**Comment by kungknut** [comment]
I assume you refer to using the variant with an own class handling the translations? Then the translations are intended to load at object creation, cached to a variable in the class context. Like the changes implemented in Auth.php through #260.

**Comment by Conver** [comment]
Good, then it will be like the config class, where all config are loaded into the class, so it doesn't need to lookup on every request.

Beside that, I think this is a good idea, thru I don't know what impact it will have on db performance if there is lots of languages to lookup.

**Comment by kungknut** [comment]
I'm glad to hear that!

My intension is to only load the preferred language, fill eventual gaps with the fallback, and let the others rest, if that's an answer to your thoughts about the database performance impact?

**Comment by kungknut** [comment]
I would appreciate some feedback/advise/second set of eyes on the changes so far.

I have intended to write a generic script reading the contents of the PHPAuth-compatible language files in a folder and insert it in database. This to let users with customized language files generate their own sql-table. The script is tested with MySQL.

I would appreciate a second pair of eyes on the Languages-class. Please note that this is not tested, nor are the changes in the Auth-class.

I have generated a separate sql-file containing the translations with the intention to make it usable on all of the supported sql-servers without modification. This is tested only in MySQL. Help is appreciated.

The table `translations` has to store data in `utf8mb4` because of the special characters used in some languages. I don't know how to make sure that table is correctly created in the other servers than MySQL. Help is appreciated.

Thanks in advance!

**Comment by Conver** [comment]
I'm making dinner right now, will go thru the code after and let you know my feedback.

**Comment by Conver** [comment]
I'm sorry. I will not be able to go thru it today, need to head out now.

**Comment by kungknut** [comment]
I would appreciate a second pair of eyes on the Languages-class. Please note that this is not tested, nor are the changes in the Auth-class. **This has been tested and corrections made**

The table translations has to store data in utf8mb4... **Successfully changed this to utf8**

Thanks in advance!

**Comment by kungknut** [comment]
@Conver, I would really appreciate your feedback about this PR. Thanks!

**Comment by Conver** [comment]
Yes. I just got back from my vacation today, will give you feedback ASAP

**Comment by kungknut** [comment]
Ah, I understand! Hope vacation was great! I don't mean to rush you, take your time!

**Comment by liamjack** [comment]
Thanks for your PR @kungknut. I think that storing such information in the database isn't very efficient, and this also applies for the current configuration storage system.

PHP will create a new instance of the Auth, Config and Language classes upon every request, it's the way PHP works: a new process is created for each request and they use the "Share Nothing" architecture.

So what will happen is that upon every new request, the Auth class will be instanciated, and it will go fetch the config data from the database, and then the language data from the database, and if the user is authenticated it's going to fetch the session data aswell. So that's already 3 seperate queries upon every new request, which is inefficient from my point of view.

**Comment by kungknut** [comment]
I see your point, and I can't say I disagree. Maybe a file based config and language is better after all?

If that is the case, I would really like to recommend JSON. Moving there should not be too hard. Regarding the config we could use this as an opportunity to set all the defaults inside the config class and let the JSON override that config. That means, the JSON file won't be needed if the user don't want to change anything.

The same goes for language, I really like working with JSON, although it seems quite strange to go there now as all of the language files already have a PHP-array inside of them.

What's your thoughts on this? @liamjack

**Comment by liamjack** [comment]
@kungknut JSON is an appropriate solution, and it's definitely better than a PHP array based config file. Possibly even better for a basic config file: YAML (possible downside: external requirements to parse correctly whereas JSON is built-in)

**Comment by kungknut** [comment]
@liamjack, I think that before adding another dependency it should be well thought through and there should be a need for it more than to read one config or language file where JSON would do the job just as good.

It seems to me like we reached a decision not to merge this PR but to add JSON formatted language and config files to the todo-list.

**Comment by liamjack** [comment]
@kungknut Indeed, it's a shame to discard your work but I think this is definetely better off in flat-file storage. Thanks for your contribution.

**Pull request closed without merging**
