### PR TITLE
Added namespace

### PR DESCRIPTION
**Pull request by KarelWintersky**
see https://github.com/PHPAuth/PHPAuth/pull/81

### CODE REVIEW

**Comment by Conver** [comment]
There is some conflicts somehow, sadly git doesn't say where and what the conflicts are.

Are you up to date with this PHPAuth repo?, there was some commits the other day.

**Comment by KarelWintersky** [comment]
Okey, I make fork and all changes again. Wait about 15 minutes...

**Comment by KarelWintersky** [comment]
close this.

**Comment by Conver** [comment]
Sure thing :)

Again, thanks for all this.. We wanted to update this class for long time, but we are both very busy.

Maybe you are up to helping with some of the other things we have on the todo list for PHPAuth?

**Comment by KarelWintersky** [comment]
https://github.com/PHPAuth/PHPAuth/pull/86

**Comment by KarelWintersky** [comment]
```
Maybe you are up to helping with some of the other things we have on the todo list for PHPAuth?
```

May be :) 
next will be lang-file for russian language and article about using your library... on russian, of course.

**Comment by Conver** [comment]
oh, that would be a wonderful thing, indeed.. the more languages the better.

Maybe we should add a todo page on the wiki for this, so we can add what we need done and such.

**Comment by KarelWintersky** [comment]
it is a lot of more little changes in my fork:

1. more config values:
```
('27','register_password_min_length','3'),
('28','register_password_max_length','150'),
('29','register_password_strong_regidity','1'),
('30','register_email_min_length','5'),
('31','register_email_max_length','100'),
('32','register_email_use_banlist','1');
```
and implementation of this

2. 
PHPAuth\Auth::__construct() patch:
```
        if (version_compare(phpversion(), '5.4.0', '<')) {
            die('PHP 5.4.0 required for PHPAuth engine!');
        }
```

and so on...

**Comment by KarelWintersky** [comment]
Of course, public todo list will be useful :)

**Comment by Conver** [comment]
Good idea to add those config values, I think its on my todo list aswell.

The: PHPAuth\Auth::__construct() - please see: https://github.com/PHPAuth/PHPAuth/pull/86#issuecomment-139416030


Will add the todo list now

**Comment by Conver** [comment]
see: Todo list

**Comment by KarelWintersky** [comment]
+

**Comment by Conver** [comment]
@KarelWintersky invited you to join the developer team of PHPAuth, that way you'll be able to edit wiki too.

**Pull request closed without merging**
