### PR TITLE
Added a feature to config if admin wants to suppress activation email (but keep activation token functionality).

### PR DESCRIPTION
**Pull request by ChristinMilloy**
I think I covered all the bases here. Default behaviour has not been affected, but activation email message can now be suppressed by config. Activation logic is otherwise unchanged.

My team wants to mass-create users and retain activation functionality, but not have PHPAuth sending the activation emails. The new feature allows this.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/113%23issuecomment-141145471%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/113%23issuecomment-141146628%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/113%23issuecomment-141151518%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/113%23issuecomment-141155860%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/113%23issuecomment-141145471%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22BTW%20it%20is%20my%20intention%20to%20create%20similar%20suppression%20options%20for%20a%20couple%20of%20the%20other%20email%20messages%20as%20well%2C%20to%20support%20my%20client%27s%20use%20case%20%28e.g.%20we%20want%20to%20do%20password%20resets%20and%20such%20without%20PHPAuth%20generating%20emails%20to%20the%20user%29%22%2C%20%22created_at%22%3A%20%222015-09-17T16%3A48%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4187179%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ChristinMilloy%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20that%20the%20line%20736%5Cr%5Cn%5Cr%5Cnif%28%21%24mail-%3Esend%28%29%20%26%26%20%21%24suppressed%29%20%7B%5Cr%5Cn%5Cr%5Cnsends%20the%20%28empty%29%20email%20even%20if%20suppressed%20is%20false.%5Cr%5CnPHP%20%20performs%20the%20checks%20based%20on%20operator%20precedence%20and%20then%20left%20to%20right.%20So%3A%5Cr%5Cn%5Cr%5Cn1%29%20executes%20%24mail-%3Esend%28%29%5Cr%5Cn-%3E%20if%20it%20returns%20false%2C%20exit%20with%20false%5Cr%5Cn-%3E%20if%20it%20returns%20true%2C%20evaluates%20%24suppressed%5Cr%5Cn%5Cr%5CnYou%20need%20to%20to%20split%20the%20if%20or%20invert%20it%2C%20like%20this%3A%5Cr%5Cn%5Cr%5Cnif%28%21%24suppressed%20%26%26%20%21%24mail-%3Esend%28%29%20%29%20%7B%5Cr%5Cn%5Cr%5CnIn%20this%20case%20if%20is%20not%20suppressed%20executes%20also%20mail-%3Esend%28%29%2C%20in%20case%20of%20suppressed%20%3D%20true%20the%20evaluation%20stops%20because%20it%20can%20be%20false%20only.%5Cr%5Cn%5Cr%5Cn%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-09-17T16%3A53%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4438193%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/bugada%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40bugada%3A%20You%20are%20correct%20that%20will%20send%20the%20email%2C%20get%20the%20return%20value%2C%20then%20check%20if%20%60%24suppressed%60%20is%20false.%22%2C%20%22created_at%22%3A%20%222015-09-17T17%3A04%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/821228%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cuonic%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-09-17T17%3A16%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Conver%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/Conver%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/Conver'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/PHPAuth/PHPAuth/pull/113#issuecomment-141145471'>General Comment</a></b>
- <a href='https://github.com/ChristinMilloy'></a> BTW it is my intention to create similar suppression options for a couple of the other email messages as well, to support my client's use case (e.g. we want to do password resets and such without PHPAuth generating emails to the user)
- <a href='https://github.com/bugada'></a> I think that the line 736
if(!$mail->send() && !$suppressed) {
sends the (empty) email even if suppressed is false.
PHP  performs the checks based on operator precedence and then left to right. So:
1) executes $mail->send()
-> if it returns false, exit with false
-> if it returns true, evaluates $suppressed
You need to to split the if or invert it, like this:
if(!$suppressed && !$mail->send() ) {
In this case if is not suppressed executes also mail->send(), in case of suppressed = true the evaluation stops because it can be false only.
- <a href='https://github.com/cuonic'></a> @bugada: You are correct that will send the email, get the return value, then check if `$suppressed` is false.

<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/113?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/113?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/113?approve=0'></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/113'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by Conver** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/PHPAuth/PHPAuth/pull/113'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by ChristinMilloy** [comment]
BTW it is my intention to create similar suppression options for a couple of the other email messages as well, to support my client's use case (e.g. we want to do password resets and such without PHPAuth generating emails to the user)

**Comment by bugada** [comment]
I think that the line 736

if(!$mail->send() && !$suppressed) {

sends the (empty) email even if suppressed is false.
PHP  performs the checks based on operator precedence and then left to right. So:

1) executes $mail->send()
-> if it returns false, exit with false
-> if it returns true, evaluates $suppressed

You need to to split the if or invert it, like this:

if(!$suppressed && !$mail->send() ) {

In this case if is not suppressed executes also mail->send(), in case of suppressed = true the evaluation stops because it can be false only.

**Comment by cuonic** [comment]
@bugada: You are correct that will send the email, get the return value, then check if `$suppressed` is false.

**Comment by Conver** [comment]
:shipit:

**Comment by JacquesLoubser** [comment]
Is it possible to trigger suppress with a boolean as well? Use cases would be if an admin wants to change another users' password without notifying them.(in a company type system)
Also the answer would be 
```php
if($suppressed){
$this->lang["register_success"] = $this->lang["register_success_emailmessage_suppressed"];
$return['error'] = false;
 		return $return;
}
if(!$mail->send()) {
 			$this->deleteRequest($request_id);
 
 			$return['message'] = $this->lang["system_error"] . " #10";
 			return $return;
 		}
```

**Comment by ChristinMilloy** [comment]
You're right. Great catch! I'll implement.

**Comment by bugada** [comment]
Yes but the email sent is empty. What's the reason for sending it? Or am I wrong?

**Comment by ChristinMilloy** [comment]
It passed my testing because I didn't receive anything. But it is being generated (into oblivion?) and this isn't a good practice. I'm doing the change suggested by JaquesLoubser.

**Comment by bugada** [comment]
Ok. Probably in a perfect world I would set $suppressed on it's declaration with the config, avoiding the following else.

**Comment by ChristinMilloy** [comment]
Ah, but i'll be adding a similar config option to suppress the password
reset emails as well, and in order to support both options in either
configuration, I need to use this set / reset approach because of the
if($type == "activation") conditional. Unless we refactor the blocks
entirely. The other option would be to repeat the references to the config
option itself repeatedly (which I don't like).

Does any other option jump out at you?

*Christin Milloy*
chrismilloy.ca*  |  @chrinfinity <https://twitter.com/chrinfinity>*

**Comment by bugada** [comment]
Ok, that makes sense. Proceed with your solution, then we have time to make it beautiful :-)

**Pull request merged**
