### PR TITLE
File Cleanup

### PR DESCRIPTION
**Pull request by livmackintosh**
Deleted old class files (*.class.php) and updated licence to MIT in composer.json.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/141%23issuecomment-148098012%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/141%23issuecomment-148098724%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/141%23issuecomment-148100871%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/141%23issuecomment-148101142%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/141%23issuecomment-148098012%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22All%20this%20actually%20changes%20is%20%60composer.json%60%20on%20line%207%20to%20%60%5C%22license%5C%22%3A%20%5C%22MIT%5C%22%2C%60%20right%20%3F%20It%20seems%20a%20bit%20overkill.%22%2C%20%22created_at%22%3A%20%222015-10-14T15%3A58%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/821228%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cuonic%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%20takes%20like%202%20minutes%20to%20branch%20edit%20and%20do%20a%20PR%20so%20what%27s%20%27overkill%27%3F%20%3Ajoy_cat%3A%20%5Cr%5Cn%5Cr%5CnLiv%22%2C%20%22created_at%22%3A%20%222015-10-14T16%3A00%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4807497%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/livmackintosh%22%7D%7D%2C%20%7B%22body%22%3A%20%22If%20you%27re%20wondering%20about%20the%203%20Merge%20commits%20-%20they%27re%20just%20from%20a%20%27git%20pull%27%20to%20update%20my%20branch%20haha%22%2C%20%22created_at%22%3A%20%222015-10-14T16%3A05%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4807497%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/livmackintosh%22%7D%7D%2C%20%7B%22body%22%3A%20%22The%20overkill%20part%20is%20all%20the%20previous%20pulls%2C%20normally%20that%20happens%20behind%20the%20scenes%20on%20your%20end%20with%20%60git%20pull%60%20magic%2C%20but%20hey%21%20Accepted.%22%2C%20%22created_at%22%3A%20%222015-10-14T16%3A06%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/821228%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cuonic%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/PHPAuth/PHPAuth/pull/141#issuecomment-148098012'>General Comment</a></b>
- <a href='https://github.com/cuonic'></a> All this actually changes is `composer.json` on line 7 to `"license": "MIT",` right ? It seems a bit overkill.
- <a href='https://github.com/livmackintosh'></a> It takes like 2 minutes to branch edit and do a PR so what's 'overkill'? :joy_cat:
Liv
- <a href='https://github.com/livmackintosh'></a> If you're wondering about the 3 Merge commits - they're just from a 'git pull' to update my branch haha
- <a href='https://github.com/cuonic'></a> The overkill part is all the previous pulls, normally that happens behind the scenes on your end with `git pull` magic, but hey! Accepted.

<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/141?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/141?approve=1'></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/141'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by Conver** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/PHPAuth/PHPAuth/pull/141'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by cuonic** [comment]
All this actually changes is `composer.json` on line 7 to `"license": "MIT",` right ? It seems a bit overkill.

**Comment by livmackintosh** [comment]
It takes like 2 minutes to branch edit and do a PR so what's 'overkill'? :joy_cat: 

Liv

**Comment by livmackintosh** [comment]
If you're wondering about the 3 Merge commits - they're just from a 'git pull' to update my branch haha

**Comment by cuonic** [comment]
The overkill part is all the previous pulls, normally that happens behind the scenes on your end with `git pull` magic, but hey! Accepted.

**Pull request merged**
