### PR TITLE
feature: config to suppress password reset email message.

### PR DESCRIPTION
**Pull request by ChristinMilloy**
Same as functionality for suppressing the activation email.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/118%23issuecomment-142037840%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/118%23issuecomment-142040187%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/118%23issuecomment-142040679%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/118%23issuecomment-142043660%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/118%23issuecomment-142037840%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20think%20this%20is%20already%20fixed%20%22%2C%20%22created_at%22%3A%20%222015-09-21T16%3A41%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5149016%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/JacquesLoubser%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20you%27re%20right.%20How%20can%20I%20cancel%20this%3F%22%2C%20%22created_at%22%3A%20%222015-09-21T16%3A49%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4187179%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ChristinMilloy%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20you%20can%20do%20a%20revert.%22%2C%20%22created_at%22%3A%20%222015-09-21T16%3A50%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4438193%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/bugada%22%7D%7D%2C%20%7B%22body%22%3A%20%22Okay%2C%20that%20was%20an%20ordeal%2C%20but%20I%20think%20I%27m%20up%20to%20date%20now.%22%2C%20%22created_at%22%3A%20%222015-09-21T17%3A03%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4187179%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ChristinMilloy%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/PHPAuth/PHPAuth/pull/118#issuecomment-142037840'>General Comment</a></b>
- <a href='https://github.com/JacquesLoubser'></a> I think this is already fixed
- <a href='https://github.com/ChristinMilloy'></a> I think you're right. How can I cancel this?
- <a href='https://github.com/bugada'></a> I think you can do a revert.
- <a href='https://github.com/ChristinMilloy'></a> Okay, that was an ordeal, but I think I'm up to date now.

<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/118?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/118?approve=1'></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/118'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by Conver** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/PHPAuth/PHPAuth/pull/118'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by JacquesLoubser** [comment]
I think this is already fixed

**Comment by ChristinMilloy** [comment]
I think you're right. How can I cancel this?

**Comment by bugada** [comment]
I think you can do a revert.

**Comment by ChristinMilloy** [comment]
Okay, that was an ordeal, but I think I'm up to date now.

**Pull request closed without merging**
