### PR TITLE
added travis validation check

### PR DESCRIPTION
**Pull request by mooztik**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/PHPAuth/PHPAuth/pull/131%23issuecomment-145400831%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/131%23issuecomment-145401951%22%2C%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/131%23issuecomment-145406320%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/PHPAuth/PHPAuth/pull/131%23issuecomment-145400831%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20would%20not%20do%20this%20until%20we%20have%20some%20actual%20tests%20running%2C%20but%20it%20needs%20to%20be%20done.%20%22%2C%20%22created_at%22%3A%20%222015-10-04T23%3A23%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5149016%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/JacquesLoubser%22%7D%7D%2C%20%7B%22body%22%3A%20%22true%2C%20a%20little%20to%20early%22%2C%20%22created_at%22%3A%20%222015-10-04T23%3A32%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1687538%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/mooztik%22%7D%7D%2C%20%7B%22body%22%3A%20%22On%20hold%22%2C%20%22created_at%22%3A%20%222015-10-05T00%3A53%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6231022%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Conver%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/PHPAuth/PHPAuth/pull/131#issuecomment-145400831'>General Comment</a></b>
- <a href='https://github.com/JacquesLoubser'></a> I would not do this until we have some actual tests running, but it needs to be done.
- <a href='https://github.com/mooztik'></a> true, a little to early
- <a href='https://github.com/Conver'></a> On hold

<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/131?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/PHPAuth/PHPAuth/pull/131?approve=1'></a>&nbsp;<a href='https://github.com/PHPAuth/PHPAuth/pull/131'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by Conver** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/PHPAuth/PHPAuth/pull/131'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by JacquesLoubser** [comment]
I would not do this until we have some actual tests running, but it needs to be done.

**Comment by mooztik** [comment]
true, a little to early

**Comment by Conver** [comment]
On hold

**Pull request merged**
