### PR TITLE
Renamed group to translation_group for database-stored translations.

### PR DESCRIPTION
**Pull request by TonyBogdanov**
Very similarly to https://github.com/PHPAuth/PHPAuth/pull/376 `group` is (also) a reserved MySQL keyword.

### CODE REVIEW

**Comment by Conver** [comment]
It's not enough just to edit the db file, the code needs to be edited aswell, see how #376 did it.

**Comment by TonyBogdanov** [comment]
I did a search through the code but couldn't find anywhere that `group` was actually being used. Am I missing something?

**Comment by Conver** [comment]
I'm not sure what that field is used for, I can't find anywhere it's used, so i'll approve.

**Comment by KarelWintersky** [comment]
This field is used only for better grouping messages in table.

**Comment by KarelWintersky** [comment]
Also, `group` (reserved word) for column name is not an error, 'cause we can use backticks.

See https://stackoverflow.com/questions/9800075/reserved-word-in-column-name-insert-into-mysql

**Pull request merged**
