### PR TITLE
Integrated update for PHPAuth

### PR DESCRIPTION
**Pull request by KarelWintersky**
**Database:**
```
* database schemes moved to separate directory
* changed names of some tables
* changed names of sime files
+ added translation table
+ added value `core_translation_source` (file | database | ini)
* renamed config key for table with banned email-domains
```

**Languages:**
`+ added return statement`

**System:**
```
+ added .gitattributes
+ added Language.php -> SQL import script
```

**Composer:**
`+ changed PHPMail version to latest`

**Auth:**
```
- loading language file moved to Config
+ added __lang() method, required for translation messages
* addRequest now uses do_SendMail() method
+ do_SendMail() method
* isEmailBanned() table existance check
! renamed config key for table with banned email-domains
* Changed magic call from $this->lang->message to $this->__lang(message)
```

**Config**
```
+ added check config table exists
+ setForgottenDictionary() method
+ added loading message translations data
+ check core tables existance
+ check & set default config table (given '' or NULL in Config() call means default `phpauth_config` table)
+ check default language (given '' or NULL 3rd arg in Config() call means default `en_GB` language)
```

### CODE REVIEW

**Comment by KarelWintersky** [comment]
travis failed due to change database

**Comment by KarelWintersky** [comment]
SQL definitions moved to `/database_defs` folder
```
$ mysql -u root phpauthtest < database_mysql.sql
/home/travis/.travis/job_stages: line 57: database_mysql.sql: No such file or directory
The command "mysql -u root phpauthtest < database_mysql.sql" failed and exited with 1 during .
```

**Comment by Conver** [comment]
Is this ready to be merged?

**Comment by KarelWintersky** [comment]
@Conver , I think, yes. It is ready to be merged. 

I solved differences

**Comment by Conver** [comment]
Can't merge, conflicts:
 Auth.php
README.md
database_informix.sql
database_mssql.sql
database_mysql.sql
database_pgsql.sql

**Comment by KarelWintersky** [comment]
Can't understand, how to resolve it.

I **moved** database files to other folder and added A LOT OF fixes to Auth.php

**Comment by Conver** [comment]
@KarelWintersky, I've added you to the trusted group, so you can merge yourself.

**Pull request merged**
